spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: gtagdvgsf1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081